name: Publish Website

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      shell: bash

    - name: Deploy to Server
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
      run: |
        sudo mkdir -p /var/www/guess-the-state/html
        scp -P $SSH_PORT -r ./* $SSH_USER@$SSH_HOST:/var/www/guess-the-state/html
        ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "chmod -R 755 /var/www/guess-the-state/html"
      shell: bash
